# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tk < Formula
  desc "Example binary distribution using homebrew."
  homepage "https://github.com/thiskevinwang/tk"
  version "0.0.7"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thiskevinwang/tk/releases/download/v0.0.7/homebrew-go-example_0.0.7_Darwin_x86_64.tar.gz"
      sha256 "23c38b7aeddca3836796b9b4027516afeea5dda1d97d0366d141063492855c4f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thiskevinwang/tk/releases/download/v0.0.7/homebrew-go-example_0.0.7_Linux_x86_64.tar.gz"
      sha256 "14cc3a4d27a22da73b155fde4e4bafa1a25094dbe88b47c6a995b8253f561ee6"
    end
  end

  def install
    bin.install "tk"
  end
end
